services:
  - type: web
    name: smartscaling-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python -c "from app.model import train_model; train_model()"
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true
    plan: free 